[package]
name = "opent_a2l_forge"
version = "0.1.0"
description = "OpenT A2L Forge"
authors = ["you"]
edition = "2021"
default-run = "opent_a2l_forge"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "opent_a2l_forge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = []
cli = []

[[bin]]
name = "opent_a2l_forge_cli"
path = "src/bin/opent_a2l_forge_cli.rs"
required-features = ["cli"]

[[bin]]
name = "opent_a2l_forge"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
a2lfile = { path = "../external/a2lfile/a2lfile" }
goblin = "0.8"
gimli = "0.31"
notify = "6"
pathdiff = "0.2"
